### PR TITLE
Added install target and using updated submodule

### PR DESCRIPTION
**Pull request by 4c0n**
Just adding some install targets again :) Could not create this PR before because it depended on the memorymap repository pr getting merged first.

Thanks in advance :1st_place_medal: :100:

### CODE REVIEW

**Comment by 4c0n** [comment]
@bweir Could you spare a little time on this please? Thank you! :smiling_face_with_three_hearts:

**Comment by 4c0n** [comment]
@bweir ping

**Comment by 4c0n** [comment]
@bweir Hi Brett, could you check this out please?

**Comment by 4c0n** [comment]
@bweir are you :ghost: ing me?

**Comment by bweir** [comment]
Sorry this is so late. I'm going to spend some time building out the CI so that it'd be possible to make releases again. The old Travis configs atrophied away, and in any case, Travis seems like its going downhill. Gotta replace all the old CI with Actions or otherwise.

**Comment by 4c0n** [comment]
@bweir Awesome :smiley:  thanks for the merge, I updated the repository url and opened a PR on flathub a while a go!

https://github.com/flathub/flathub/pull/1904

The build was passing not long ago, so it shouldn't be long before it's available through flathub :tada:

**Comment by bweir** [comment]
Awesome! Question, how does this connect to CI? So for example, when it's
time to make a new release, how can we set it up to push a new release to
flathub?

**Comment by 4c0n** [comment]
@bweir the manifest file will end up in its own repository flathub/com.parallax.PropellerIDE and it contains the version number and the git commit hash.
When you push to the new repository it should schedule a build and eventually push a new release, so you might want to somehow generate/modify the manifest from the CI here I suppose. Maybe there already is an action available to generate json configuration files and a way for it to access another repository, wouldn't be surprised 🙂

**Comment by barthalion** [comment]
You can take a look at https://github.com/flathub/io.openrct2.OpenRCT2/pull/5 – it's used for beta builds, but should be easy to use only "tags" events. (Using Flathub as CI for every commit is not recommended as we have limited resources.)

**Pull request merged**
